# Generated by Django 6.0 on 2025-12-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title_uk', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('short_uk', models.TextField(blank=True, default='')),
                ('short_en', models.TextField(blank=True, default='')),
                ('body_uk', models.TextField(blank=True, default='')),
                ('body_en', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
