# Generated by Django 6.0 on 2025-12-18 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='body_uk',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='short_en',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='short_uk',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='content_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='content_uk',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/covers/'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='short_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='short_description_uk',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='title_en',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='CatalogItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/gallery/')),
                ('caption_uk', models.CharField(blank=True, max_length=255)),
                ('caption_en', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.catalogitem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
