# Generated by Django 6.0 on 2025-12-18 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_catalogitem_options_remove_catalogitem_body_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogitem',
            options={},
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='content_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='content_uk',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='short_description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='short_description_uk',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='CatalogGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/gallery/')),
                ('caption_uk', models.CharField(blank=True, default='', max_length=255)),
                ('caption_en', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.catalogitem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='CatalogItemImage',
        ),
    ]
