# Generated by Django 6.0 on 2025-12-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_catalogitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='catalog/pdfs/'),
        ),
    ]
