# Generated by Django 6.0 on 2025-12-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Unique identifier for the page (e.g., 'about-summary')", unique=True)),
                ('title_uk', models.CharField(max_length=200, verbose_name='Title (Ukrainian)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('content_uk', models.TextField(blank=True, verbose_name='Content (Ukrainian)')),
                ('content_en', models.TextField(blank=True, verbose_name='Content (English)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='page_images/')),
                ('chart_data', models.JSONField(blank=True, help_text='JSON data for charts (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
