# Generated by Django 6.0 on 2025-12-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='EconomyContent',
            fields=[
            ],
            options={
                'verbose_name': 'Economy Page',
                'verbose_name_plural': 'Economy Pages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='GeneralContent',
            fields=[
            ],
            options={
                'verbose_name': 'General Page',
                'verbose_name_plural': 'General Pages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='InvestmentContent',
            fields=[
            ],
            options={
                'verbose_name': 'Investment Page',
                'verbose_name_plural': 'Investment Pages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='section',
            field=models.CharField(choices=[('general', 'General'), ('about', 'About Region'), ('economy', 'Economy'), ('investment', 'Investment')], default='general', max_length=20, verbose_name='Section'),
        ),
    ]
