# Generated by Django 6.0 on 2025-12-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_aboutcontent_economycontent_generalcontent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutContent',
        ),
        migrations.DeleteModel(
            name='EconomyContent',
        ),
        migrations.DeleteModel(
            name='GeneralContent',
        ),
        migrations.DeleteModel(
            name='InvestmentContent',
        ),
        migrations.CreateModel(
            name='AdvantagesPage',
            fields=[
            ],
            options={
                'verbose_name': '2. Advantages',
                'verbose_name_plural': '2. Advantages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='AgriculturePage',
            fields=[
            ],
            options={
                'verbose_name': '2. Agriculture',
                'verbose_name_plural': '2. Agriculture',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='CatalogPage',
            fields=[
            ],
            options={
                'verbose_name': '2. Catalog',
                'verbose_name_plural': '2. Catalog',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='EducationPage',
            fields=[
            ],
            options={
                'verbose_name': '6. Education',
                'verbose_name_plural': '6. Education',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='EnergyPage',
            fields=[
            ],
            options={
                'verbose_name': '4. Energy',
                'verbose_name_plural': '4. Energy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='IndustryPage',
            fields=[
            ],
            options={
                'verbose_name': '1. Industry',
                'verbose_name_plural': '1. Industry',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='InfrastructurePage',
            fields=[
            ],
            options={
                'verbose_name': '3. Infrastructure',
                'verbose_name_plural': '3. Infrastructure',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='InternationalPage',
            fields=[
            ],
            options={
                'verbose_name': '5. International Cooperation',
                'verbose_name_plural': '5. International Cooperation',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='ITPage',
            fields=[
            ],
            options={
                'verbose_name': '8. IT Sector',
                'verbose_name_plural': '8. IT Sector',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='MineralsPage',
            fields=[
            ],
            options={
                'verbose_name': '3. Minerals',
                'verbose_name_plural': '3. Minerals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='OpportunitiesPage',
            fields=[
            ],
            options={
                'verbose_name': '1. Opportunities',
                'verbose_name_plural': '1. Opportunities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='ParksPage',
            fields=[
            ],
            options={
                'verbose_name': '6. Industrial Parks',
                'verbose_name_plural': '6. Industrial Parks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='ProjectsPage',
            fields=[
            ],
            options={
                'verbose_name': '4. Projects',
                'verbose_name_plural': '4. Projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='RelocatedPage',
            fields=[
            ],
            options={
                'verbose_name': '7. Relocated Enterprises',
                'verbose_name_plural': '7. Relocated Enterprises',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='SummaryPage',
            fields=[
            ],
            options={
                'verbose_name': '1. Summary',
                'verbose_name_plural': '1. Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='TastingHallsPage',
            fields=[
            ],
            options={
                'verbose_name': '3. Tasting Halls',
                'verbose_name_plural': '3. Tasting Halls',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='TaxationPage',
            fields=[
            ],
            options={
                'verbose_name': '5. Taxation',
                'verbose_name_plural': '5. Taxation',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.CreateModel(
            name='TourismPage',
            fields=[
            ],
            options={
                'verbose_name': '4. Tourism',
                'verbose_name_plural': '4. Tourism',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='slug',
            field=models.SlugField(help_text='Unique identifier for the page', unique=True),
        ),
    ]
