# Generated by Django 6.0 on 2025-12-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_delete_aboutcontent_delete_economycontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='chart_data',
            field=models.JSONField(blank=True, help_text='\n    Example:\n    {\n      "columns": ["Source", "Potential", "Installed"],\n      "rows": [\n        {"label": "Solar", "values": [100, 20]},\n        {"label": "Wind", "values": [200, 50]}\n      ]\n    }\n    ', null=True),
        ),
    ]
