# Generated by Django 6.0 on 2025-12-12 09:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_pagecontent_chart_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomyMainPage',
            fields=[
            ],
            options={
                'verbose_name': 'Економіка (Головна)',
                'verbose_name_plural': 'Економіка (Головна)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagecontent',),
        ),
        migrations.AlterModelOptions(
            name='advantagespage',
            options={'verbose_name': '2. Переваги', 'verbose_name_plural': '2. Переваги'},
        ),
        migrations.AlterModelOptions(
            name='agriculturepage',
            options={'verbose_name': '2. Сільське господарство', 'verbose_name_plural': '2. Сільське господарство'},
        ),
        migrations.AlterModelOptions(
            name='catalogpage',
            options={'verbose_name': '2. Каталог', 'verbose_name_plural': '2. Каталог'},
        ),
        migrations.AlterModelOptions(
            name='educationpage',
            options={'verbose_name': '6. Освіта', 'verbose_name_plural': '6. Освіта'},
        ),
        migrations.AlterModelOptions(
            name='energypage',
            options={'verbose_name': '4. Енергетика', 'verbose_name_plural': '4. Енергетика'},
        ),
        migrations.AlterModelOptions(
            name='industrypage',
            options={'verbose_name': '1. Промисловість', 'verbose_name_plural': '1. Промисловість'},
        ),
        migrations.AlterModelOptions(
            name='infrastructurepage',
            options={'verbose_name': '3. Інфраструктура', 'verbose_name_plural': '3. Інфраструктура'},
        ),
        migrations.AlterModelOptions(
            name='internationalpage',
            options={'verbose_name': '5. Міжнародна співпраця', 'verbose_name_plural': '5. Міжнародна співпраця'},
        ),
        migrations.AlterModelOptions(
            name='itpage',
            options={'verbose_name': '8. IT-сектор', 'verbose_name_plural': '8. IT-сектор'},
        ),
        migrations.AlterModelOptions(
            name='mineralspage',
            options={'verbose_name': '3. Корисні копалини', 'verbose_name_plural': '3. Корисні копалини'},
        ),
        migrations.AlterModelOptions(
            name='opportunitiespage',
            options={'verbose_name': '1. Можливості', 'verbose_name_plural': '1. Можливості'},
        ),
        migrations.AlterModelOptions(
            name='parkspage',
            options={'verbose_name': '6. Індустріальні парки', 'verbose_name_plural': '6. Індустріальні парки'},
        ),
        migrations.AlterModelOptions(
            name='projectspage',
            options={'verbose_name': '4. Проєкти', 'verbose_name_plural': '4. Проєкти'},
        ),
        migrations.AlterModelOptions(
            name='relocatedpage',
            options={'verbose_name': '7. Релоковані підприємства', 'verbose_name_plural': '7. Релоковані підприємства'},
        ),
        migrations.AlterModelOptions(
            name='summarypage',
            options={'verbose_name': '1. Огляд', 'verbose_name_plural': '1. Огляд'},
        ),
        migrations.AlterModelOptions(
            name='tastinghallspage',
            options={'verbose_name': '3. Дегустаційні зали', 'verbose_name_plural': '3. Дегустаційні зали'},
        ),
        migrations.AlterModelOptions(
            name='taxationpage',
            options={'verbose_name': '5. Оподаткування', 'verbose_name_plural': '5. Оподаткування'},
        ),
        migrations.AlterModelOptions(
            name='tourismpage',
            options={'verbose_name': '4. Туризм', 'verbose_name_plural': '4. Туризм'},
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Content (English)'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='content_uk',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Content (Ukrainian)'),
        ),
    ]
