# Generated by Django 6.0 on 2025-12-12 12:08

from django_ckeditor_5.fields import CKEditor5Field
import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_economymainpage_alter_advantagespage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('title_uk', models.CharField(max_length=200, verbose_name='Назва (українською)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('description_uk', models.TextField(blank=True, verbose_name='Опис (українською)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='Показувати в меню')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сторінка',
                'verbose_name_plural': 'Динамічні сторінки',
                'ordering': ['order', 'title_uk'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('text', 'Текстовий контент'), ('image', 'Зображення'), ('video', 'Відео'), ('gallery', 'Галерея зображень'), ('embed', 'Вбудований контент')], default='text', max_length=20, verbose_name='Тип секції')),
                ('title_uk', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (українською)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Title (English)')),
                ('content_uk', CKEditor5Field(blank=True, verbose_name='Контент (українською)')),
                ('content_en', CKEditor5Field(blank=True, verbose_name='Content (English)')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('video', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video')),
                ('embed_code', models.TextField(blank=True, verbose_name='Код вбудовування')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.page', verbose_name='Сторінка')),
            ],
            options={
                'verbose_name': 'Секція сторінки',
                'verbose_name_plural': 'Секції сторінки',
                'ordering': ['order'],
            },
        ),
    ]
