# Generated by Django 6.0 on 2025-12-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_page_pagesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='menu_category',
            field=models.CharField(choices=[('none', 'Не в меню'), ('about', 'Про регіон'), ('economy', 'Економіка'), ('investment', 'Інвестиції')], default='none', max_length=20, verbose_name='Категорія меню'),
        ),
    ]
