# Generated by Django 6.0 on 2025-12-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_page_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='section_images/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='section_videos/', verbose_name='Відео'),
        ),
    ]
