# Generated by Django 6.0 on 2025-12-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_pagesection_image_alter_pagesection_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='chart_data',
            field=models.JSONField(blank=True, help_text="Example: {'labels': ['Jan', 'Feb'], 'datasets': [{'label': 'Potential', 'data': [10, 20]}]}", null=True, verbose_name='Дані графіку (JSON)'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero (Full-screen Video/Image)'), ('text', 'Текстовий контент'), ('image', 'Зображення'), ('video', 'Відео'), ('gallery', 'Галерея зображень'), ('chart', 'Графік / Діаграма'), ('stats', 'Статистика / KPI'), ('embed', 'Вбудований контент'), ('custom', 'Raw HTML / Custom')], default='text', max_length=20, verbose_name='Тип секції'),
        ),
    ]
