# Generated by Django 6.0 on 2025-12-28 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_pagesection_chart_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(blank=True, max_length=200, verbose_name='Заголовок елемента (українською)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Title (English)')),
                ('description_uk', models.TextField(blank=True, verbose_name='Опис елемента (українською)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='Зображення')),
                ('file', models.FileField(blank=True, null=True, upload_to='item_files/', verbose_name='Файл (PDF)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.pagesection', verbose_name='Секція')),
            ],
            options={
                'verbose_name': 'Елемент секції',
                'verbose_name_plural': 'Елементи секції',
                'ordering': ['order'],
            },
        ),
    ]
