# Generated by Django 6.0 on 2025-12-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_pagesectionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero (Full-screen Video/Image)'), ('text', 'Текстовий контент'), ('image', 'Зображення'), ('video', 'Відео'), ('gallery', 'Галерея зображень'), ('chart', 'Графік / Діаграма'), ('stats', 'Статистика / KPI'), ('embed', 'Вбудований контент'), ('grid', 'Сітка документів (PDF/Grid)'), ('custom', 'Raw HTML / Custom')], default='text', max_length=20, verbose_name='Тип секції'),
        ),
    ]
