# Generated by Django 6.0 on 2025-12-29 08:20

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_pagesection_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesectionitem',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Full Content (English)'),
        ),
        migrations.AddField(
            model_name='pagesectionitem',
            name='content_uk',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Детальний контент (українською)'),
        ),
        migrations.AlterField(
            model_name='pagesectionitem',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Short Description (English)'),
        ),
        migrations.AlterField(
            model_name='pagesectionitem',
            name='description_uk',
            field=models.TextField(blank=True, verbose_name='Короткий опис (українською)'),
        ),
    ]
