# Generated by Django 6.0 on 2025-12-29 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_pagesectionitem_content_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSectionItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_gallery/', verbose_name='Зображення')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.pagesectionitem', verbose_name='Елемент')),
            ],
            options={
                'verbose_name': 'Зображення галереї',
                'verbose_name_plural': 'Галерея зображень',
                'ordering': ['order'],
            },
        ),
    ]
