# Generated by Django 6.0 on 2025-12-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_pagesectionitemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesectionitem',
            name='button_text_en',
            field=models.CharField(blank=True, help_text="Default: 'View Details'", max_length=100, verbose_name='Button text (en)'),
        ),
        migrations.AddField(
            model_name='pagesectionitem',
            name='button_text_uk',
            field=models.CharField(blank=True, help_text="За замовчуванням: 'Детальніше'", max_length=100, verbose_name='Текст кнопки (укр)'),
        ),
        migrations.AddField(
            model_name='pagesectionitem',
            name='item_type',
            field=models.CharField(choices=[('card', 'Стандартна картка'), ('document', 'Документ (PDF/Файл)'), ('link', 'Зовнішнє посилання')], default='card', max_length=20, verbose_name='Тип елемента'),
        ),
    ]
